### ISSUE TITLE
The cost of running on whole dataset!

### ISSUE THREAD

**Issue by sia-watsonlee** [koa-fin/sep#5]
Hi everyone , as we all know, fine tuning is costly with gpt openai. i would be appreciated if anyone run this code on whole dataset could tell us about the API cost?

**Comment by koa-fin** [comment]
The tokens and costs for running it on 11 stocks, over 3 years, were mentioned here: [https://openreview.net/forum?id=XeI4Ou8Ncp&noteId=tUniK1jqnm](https://openreview.net/forum?id=XeI4Ou8Ncp&noteId=tUniK1jqnm) (About $103 at the time of running the experiments). 

The costs might have been changed since then.
